// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ_G413qojcUnnJr4wZpoZ7wQIgTXFQRY',
    appId: '1:589368299920:web:4a473235b37dc8a7b9a315',
    messagingSenderId: '589368299920',
    projectId: 'habitat-app-17df5',
    authDomain: 'habitat-app-17df5.firebaseapp.com',
    storageBucket: 'habitat-app-17df5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3LkvWzqWUQbGfrT9wMZl9TVgLk0fYOkA',
    appId: '1:589368299920:android:bb01297e869fafabb9a315',
    messagingSenderId: '589368299920',
    projectId: 'habitat-app-17df5',
    storageBucket: 'habitat-app-17df5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiiwMcB2t2QC0NTs9RpHP6_X3GX3__juA',
    appId: '1:589368299920:ios:e452c87f51e43d83b9a315',
    messagingSenderId: '589368299920',
    projectId: 'habitat-app-17df5',
    storageBucket: 'habitat-app-17df5.firebasestorage.app',
    iosBundleId: 'com.example.habitaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiiwMcB2t2QC0NTs9RpHP6_X3GX3__juA',
    appId: '1:589368299920:ios:e452c87f51e43d83b9a315',
    messagingSenderId: '589368299920',
    projectId: 'habitat-app-17df5',
    storageBucket: 'habitat-app-17df5.firebasestorage.app',
    iosBundleId: 'com.example.habitaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ_G413qojcUnnJr4wZpoZ7wQIgTXFQRY',
    appId: '1:589368299920:web:37ee0b66e5237961b9a315',
    messagingSenderId: '589368299920',
    projectId: 'habitat-app-17df5',
    authDomain: 'habitat-app-17df5.firebaseapp.com',
    storageBucket: 'habitat-app-17df5.firebasestorage.app',
  );
}
